- community.general.homebrew_tap:
    name: supersonic-app/supersonic

- community.general.homebrew:
    name:
      - btop
      - coreutils
      - docker-buildx
      - docker-compose
      - docker
      - exiftool
      - fish
      - gifsicle
      - gnu-sed
      - gnu-tar
      - kubernetes-cli
      - lftp
      - media-info
      - parallel
      - rename
      - ripgrep
      - stow
      - watch
      - zenity
    state: present

- community.general.homebrew_cask:
    name:
      - flox
      - font-hurmit-nerd-font
      - font-symbols-only-nerd-font
      - jordanbaird-ice
      - kitty
      - localsend
      - middleclick
      - supersonic
      - swiftbar
    state: present

- name: Dark mode
  community.general.osx_defaults:
    key: AppleInterfaceStyle
    type: string
    value: Dark

- name: Show folders before files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: int
    value: 1
