- name: Git checkout
  ansible.builtin.git:
    repo: https://github.com/sagebind/tuxedo-infinitybook-gen10-cc-plugin
    dest: ~/.local/src/tuxedo-infinitybook-gen10-cc-plugin

- name: Install CC plugin
  ansible.builtin.command:
    creates: /etc/coolercontrol/plugins/tuxedo-infinitybook-gen10/manifest.toml
    cmd: make install
    chdir: ~/.local/src/tuxedo-infinitybook-gen10-cc-plugin
