version = 1

[install]
_7zz-rar.pkg-path = "_7zz-rar"
broot.pkg-path = "broot"
choose.pkg-path = "choose"
colima.pkg-path = "colima"
colima.systems = ["aarch64-darwin"]
crane.pkg-path = "crane"
devenv.pkg-group = "devenv"
devenv.pkg-path = "devenv"
difftastic.pkg-path = "difftastic"
direnv.pkg-group = "direnv"
direnv.pkg-path = "direnv"
doctl.pkg-path = "doctl"
doggo.pkg-path = "doggo"
dust.pkg-path = "dust"
espanso-wayland.pkg-path = "espanso-wayland"
espanso-wayland.systems = ["x86_64-linux"]
eza.pkg-path = "eza"
flac.pkg-path = "flac"
gdu.pkg-path = "gdu"
gh.pkg-path = "gh"
gifski.pkg-path = "gifski"
glow.pkg-path = "glow"
hurmit.pkg-path = "nerd-fonts.hurmit"
jq.pkg-group = "jq"
jq.pkg-path = "jq"
k9s.pkg-group = "k9s"
k9s.pkg-path = "k9s"
kubectl.pkg-path = "kubectl"
kubectx.pkg-path = "kubectx"
kubernetes-helm.pkg-path = "kubernetes-helm"
libinput-gestures.pkg-path = "libinput-gestures"
libinput-gestures.systems = ["aarch64-linux", "x86_64-linux"]
miniserve.pkg-path = "miniserve"
mitmproxy.pkg-group = "mitmproxy"
mitmproxy.pkg-path = "mitmproxy"
msedit.pkg-group = "msedit"
msedit.pkg-path = "msedit"
nixfmt.pkg-group = "nixfmt"
nixfmt.pkg-path = "nixfmt"
numbat.pkg-path = "numbat"
nvtop.pkg-path = "nvtop"
pdfcpu.pkg-path = "pdfcpu"
pueue.pkg-path = "pueue"
qpdf.pkg-path = "qpdf"
regctl.pkg-group = "regctl"
regctl.pkg-path = "regctl"
rsgain.pkg-path = "rsgain"
skim.pkg-path = "skim"
sox.pkg-path = "sox"
tio.pkg-path = "tio"
tokei.pkg-path = "tokei"
tuxedo-rs.pkg-group = "tuxedo-rs"
tuxedo-rs.pkg-path = "tuxedo-rs"
tuxedo-rs.systems = ["x86_64-linux"]
uv.pkg-path = "uv"
vicinae.flake = "github:vicinaehq/vicinae/v0.16.6"
vicinae.systems = ["x86_64-linux"]
visidata.pkg-path = "visidata"
wev.pkg-path = "wev"
wev.systems = ["x86_64-linux"]
xdg-terminal-exec.pkg-path = "xdg-terminal-exec"
xdg-terminal-exec.systems = ["x86_64-linux"]
xsv.pkg-path = "xsv"
yazi.pkg-path = "yazi"
yq.pkg-group = "yq"
yq.pkg-path = "yq-go"
nmap.pkg-path = "nmap"

[options]
allow.unfree = true
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-linux",
]
